# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
java_version=25
kotlin_version=2.4.0

# Mod Properties
mod_id=fabric-language-kotlin
mod_version=1.13.12
mod_group=net.fabricmc
mod_description=Fabric language module for Kotlin

modId=fabric-language-kotlin
modVersion=1.13.12
minecraftVersion=1.20.2
mappingsVersion=1.20.2+build.4
loaderVersion=0.16.9
group=net.fabricmc
description=Fabric language module for Kotlin
