name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        java: [17, 21]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: 'Build'
        run: ./gradlew build publishMods --stacktrace --warning-mode=fail
      - name: 'Upload artifacts'
        if: ${{ matrix.java == '20' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
