name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        java: [17, 20]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: 'Build'
        run: ./gradlew build publishMods --stacktrace --warning-mode=fail

      - name: 'Upload artifacts'
        if: ${{ matrix.java == '20' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
