name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: 'temurin'
      - uses: actions/checkout@v7
      - name: 'Build'
        run: ./gradlew build publishMods --stacktrace --warning-mode=fail
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
