name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        java: [17-jdk, 18-jdk]
    runs-on: ubuntu-22.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: 'Clone Repo'
        uses: actions/checkout@v2

      - name: 'Validate Gradle Wrapper'
        uses: gradle/wrapper-validation-action@v1

      - name: 'Build'
        run: ./gradlew build --stacktrace --warning-mode=fail
