name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 14-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew -PincludeSample=false clean build --refresh-dependencies --full-stacktrace